#!/usr/bin/env bash
# Local contributor setup — provisions a fully local Superset workspace with no
# real credentials: fake env, local Postgres (docker), migrations, a seeded dev
# account, dynamic ports, and Electric. Mirrors setup.sh but replaces Neon and
# the "copy my signed-in data" seeds with a self-contained local stack.
set -uo pipefail

SUPERSET_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SUPERSET_SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# shellcheck source=/dev/null
source "$SUPERSET_SCRIPT_DIR/lib/common.sh"
# Reuse allocate_port_base, step_prepare_electric, step_start_electric,
# step_install_dependencies, write_env_var from the shared setup lib.
# shellcheck source=/dev/null
source "$SUPERSET_SCRIPT_DIR/lib/setup/steps.sh"

FORCE_OVERWRITE_DATA="${FORCE_OVERWRITE_DATA:-0}"
WORKSPACE_NAME="${SUPERSET_WORKSPACE_NAME:-$(basename "$PWD")}"

step_local_env() {
	echo "📂 Preparing .env (local)..."
	if [ -f .env ]; then
		warn ".env already exists — keeping it (delete it to regenerate)"
	else
		if [ ! -f .env.local.example ]; then
			error ".env.local.example not found in $REPO_ROOT"
			return 1
		fi
		cp .env.local.example .env
		success ".env created from .env.local.example"
	fi
	set -a
	# shellcheck source=/dev/null
	source .env
	set +a
	return 0
}

step_local_check_dependencies() {
	echo "🔍 Checking dependencies..."
	local missing=()
	command -v bun &>/dev/null || missing+=("bun (https://bun.sh)")
	command -v docker &>/dev/null || missing+=("docker (https://docker.com)")
	command -v jq &>/dev/null || missing+=("jq (brew install jq)")
	command -v caddy &>/dev/null || warn "caddy not found — Electric HTTP/2 proxy won't work (brew install caddy && caddy trust)"
	if [ ${#missing[@]} -gt 0 ]; then
		error "Missing dependencies:"
		for dep in "${missing[@]}"; do echo "  - $dep"; done
		return 1
	fi
	success "All dependencies found"
	return 0
}

step_local_start_db() {
	echo "🐘 Starting local Postgres + Neon proxy (docker compose)..."
	if ! docker compose up -d; then
		error "docker compose up failed"
		return 1
	fi
	echo "  Waiting for Postgres to be healthy..."
	local container
	container="$(docker compose ps -q postgres 2>/dev/null)"
	for _ in $(seq 1 30); do
		if [ "$(docker inspect --format '{{.State.Health.Status}}' "$container" 2>/dev/null)" = "healthy" ]; then
			success "Postgres healthy"
			return 0
		fi
		sleep 2
	done
	error "Postgres did not become healthy in time"
	return 1
}

step_local_migrate_seed() {
	echo "🗄️  Migrating schema + seeding dev account..."
	if ! bun run db:migrate; then
		error "db:migrate failed"
		return 1
	fi
	if ! bun run db:seed-dev; then
		error "db:seed-dev failed"
		return 1
	fi
	success "Schema migrated + dev account seeded (onboarded, pro)"
	return 0
}

step_local_write_env() {
	echo "📝 Writing workspace ports + URLs into .env..."
	if [ -z "${SUPERSET_PORT_BASE:-}" ]; then
		error "SUPERSET_PORT_BASE not set"
		return 1
	fi

	local BASE=$SUPERSET_PORT_BASE
	local WEB_PORT=$((BASE))
	local API_PORT=$((BASE + 1))
	local MARKETING_PORT=$((BASE + 2))
	local ADMIN_PORT=$((BASE + 3))
	local DOCS_PORT=$((BASE + 4))
	local DESKTOP_VITE_PORT=$((BASE + 5))
	local DESKTOP_NOTIFICATIONS_PORT=$((BASE + 6))
	local STREAMS_PORT=$((BASE + 7))
	local STREAMS_INTERNAL_PORT=$((BASE + 8))
	local ELECTRIC_PORT_LOCAL=$((BASE + 9))
	local CADDY_ELECTRIC_PORT=$((BASE + 10))
	local CODE_INSPECTOR_PORT=$((BASE + 11))
	local WRANGLER_PORT=$((BASE + 12))
	local RELAY_PORT=$((BASE + 13))

	{
		echo ""
		echo "# --- Local workspace overrides (generated by setup.local.sh) ---"
		write_env_var "SUPERSET_WORKSPACE_NAME" "$WORKSPACE_NAME"
		write_env_var "SUPERSET_HOME_DIR" "$PWD/superset-dev-data"
		write_env_var "SUPERSET_PORT_BASE" "$BASE"
		write_env_var "WEB_PORT" "$WEB_PORT"
		write_env_var "API_PORT" "$API_PORT"
		write_env_var "MARKETING_PORT" "$MARKETING_PORT"
		write_env_var "ADMIN_PORT" "$ADMIN_PORT"
		write_env_var "DOCS_PORT" "$DOCS_PORT"
		write_env_var "DESKTOP_VITE_PORT" "$DESKTOP_VITE_PORT"
		write_env_var "DESKTOP_NOTIFICATIONS_PORT" "$DESKTOP_NOTIFICATIONS_PORT"
		write_env_var "STREAMS_PORT" "$STREAMS_PORT"
		write_env_var "STREAMS_INTERNAL_PORT" "$STREAMS_INTERNAL_PORT"
		write_env_var "ELECTRIC_PORT" "$ELECTRIC_PORT_LOCAL"
		write_env_var "CADDY_ELECTRIC_PORT" "$CADDY_ELECTRIC_PORT"
		write_env_var "CODE_INSPECTOR_PORT" "$CODE_INSPECTOR_PORT"
		write_env_var "WRANGLER_PORT" "$WRANGLER_PORT"
		write_env_var "RELAY_PORT" "$RELAY_PORT"
		write_env_var "NEXT_PUBLIC_API_URL" "http://localhost:$API_PORT"
		write_env_var "NEXT_PUBLIC_WEB_URL" "http://localhost:$WEB_PORT"
		write_env_var "NEXT_PUBLIC_MARKETING_URL" "http://localhost:$MARKETING_PORT"
		write_env_var "NEXT_PUBLIC_ADMIN_URL" "http://localhost:$ADMIN_PORT"
		write_env_var "NEXT_PUBLIC_DOCS_URL" "http://localhost:$DOCS_PORT"
		write_env_var "NEXT_PUBLIC_DESKTOP_URL" "http://localhost:$DESKTOP_VITE_PORT"
		write_env_var "RELAY_URL" "http://localhost:$RELAY_PORT"
		write_env_var "NEXT_PUBLIC_RELAY_URL" "http://localhost:$RELAY_PORT"
		write_env_var "PORT" "$STREAMS_PORT"
		write_env_var "STREAMS_URL" "http://localhost:$STREAMS_PORT"
		write_env_var "NEXT_PUBLIC_STREAMS_URL" "http://localhost:$STREAMS_PORT"
		write_env_var "STREAMS_INTERNAL_URL" "http://127.0.0.1:$STREAMS_INTERNAL_PORT"
		write_env_var "ELECTRIC_URL" "http://localhost:$ELECTRIC_PORT_LOCAL/v1/shape"
		write_env_var "NEXT_PUBLIC_ELECTRIC_URL" "https://localhost:$CADDY_ELECTRIC_PORT"
		write_env_var "NEXT_PUBLIC_ELECTRIC_PROXY_URL" "https://localhost:$CADDY_ELECTRIC_PORT"
		if [ -n "${ELECTRIC_SECRET:-}" ]; then
			write_env_var "ELECTRIC_SECRET" "$ELECTRIC_SECRET"
		fi
		if [ -n "${ELECTRIC_CONTAINER:-}" ]; then
			write_env_var "ELECTRIC_CONTAINER" "$ELECTRIC_CONTAINER"
		fi
	} >>.env

	cat >Caddyfile <<-CADDYEOF
		{
			auto_https disable_redirects
		}

		https://localhost:{\$CADDY_ELECTRIC_PORT} {
			reverse_proxy localhost:{\$WRANGLER_PORT} {
				flush_interval -1
			}
		}
	CADDYEOF

	cat >apps/electric-proxy/.dev.vars <<DEVVARS
AUTH_URL=http://localhost:$API_PORT
ELECTRIC_SHAPE_URL=http://localhost:$ELECTRIC_PORT_LOCAL/v1/shape
ELECTRIC_SECRET=${ELECTRIC_SECRET:-local_electric_dev_secret}
ELECTRIC_SOURCE_ID=
ELECTRIC_SOURCE_SECRET=
DEVVARS

	success "Workspace ports + URLs written"
	return 0
}

step_local_update_config() {
	echo "🔧 Pointing .superset/config.json setup at setup.local.sh..."
	local config_file="$SUPERSET_SCRIPT_DIR/config.json"
	if [ ! -f "$config_file" ]; then
		warn "No config.json — skipping"
		step_skipped "Update config.json"
		return 0
	fi
	local tmp="${config_file}.tmp.$$"
	if ! jq '.setup = ["./.superset/setup.local.sh"]' "$config_file" >"$tmp"; then
		error "Failed to update config.json"
		rm -f "$tmp"
		return 1
	fi
	mv "$tmp" "$config_file"
	success "config.json setup -> ./.superset/setup.local.sh"
	return 0
}

setup_local_main() {
	FAILED_STEPS=()
	SKIPPED_STEPS=()

	echo "🚀 Setting up LOCAL Superset workspace (no real credentials)..."
	echo ""

	step_local_env || step_failed "Prepare .env"
	step_local_check_dependencies || step_failed "Check dependencies"
	step_install_dependencies || step_failed "Install dependencies"
	step_local_start_db || step_failed "Start local Postgres"
	step_local_migrate_seed || step_failed "Migrate + seed"
	allocate_port_base || step_failed "Allocate port base"

	# Electric reads logical replication directly from Postgres; from inside its
	# container the host DB is reachable via host.docker.internal, not localhost.
	export DIRECT_URL="postgres://postgres:postgres@host.docker.internal:5432/main"
	step_prepare_electric || step_failed "Prepare Electric"
	step_local_write_env || step_failed "Write workspace .env"
	if ! step_start_electric; then
		warn "Electric failed to start — the app boots but live queries won't work until it's up"
		step_skipped "Start Electric (non-fatal)"
	fi
	step_local_update_config || step_failed "Update config.json"

	print_summary "Local setup"
}

setup_local_main "$@"
